In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [3]:
df=pd.read_csv("book.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  630000
4  4000  725000

In [4]:
reg=linear_model.LinearRegression()

In [5]:
reg.fit(df[['area']],df.price)
reg.predict([[3300]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([618441.78082192])

In [6]:
reg.coef_

array([122.0890411])

In [7]:
reg.intercept_

215547.9452054794

In [8]:
import pickle

In [10]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [11]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [13]:
mp.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([825993.15068493])

In [19]:
import joblib

In [20]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [21]:
mj = joblib.load('model_joblib')

In [22]:
mj.coef_

array([122.0890411])

In [23]:
mj.intercept_

215547.9452054794

In [25]:
mj.predict([[3300]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([618441.78082192])